CREATE TABLE public.BUILDING
(
  ID SERIAL,
  NUMBER INTEGER NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE public.ROOM
(
  ID          SERIAL,
  BUILDING_ID INTEGER NOT NULL,
  NUMBER INTEGER NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID)
)

